[package]
name = "qrwatermark_php"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ext-php-rs = "*"
qrwatermark = { path = "./../qrwatermark" }

[profile.release]
strip = "debuginfo"
