[package]
name = "qrwatermark"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "qrwatermark"

[dependencies]
ext-php-rs = "*"
qrwatermark = "0.1.2"

[profile.release]
panic = "abort"
strip = true
lto = "fat"
opt-level = "z"
codegen-units = 1
