[package]
name = "qrwatermark"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "qrwatermark"

[dependencies]
ext-php-rs = "*"
qrwatermark = { path = "./../qrwatermark", version = "1.0.1" }

[profile.release]
strip = "debuginfo"
